# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('sd-manet-example', ['sd-manet' 'internet','olsr','internet', 'applications' ])
    obj.source = 'sd-manet-example.cc'

